name: Convert ONNX to CoreML

on: [push]

jobs:
  convert:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install onnx==1.13 onnx-tf==1.10.0 tensorflow==2.13.1 tensorflow-probability==0.20.0 coremltools==6.3

      - name: Convert model
        run: |
          python convert.py

      - name: Upload CoreML model
        uses: actions/upload-artifact@v4
        with:
          name: coreml-model
          path: YJ_B_5000_3layer_rgb2rgb_mlp_model.mlmodel
